export const food_data = [
  {
    id: 1,
    name: "Peanut Butter regular",
    price: 299,
    favorite: false,
    rating: 4.3,
    expiry: "6 months",
    img_URL: "pbreg.jpg",
  },
  {
    id: 2,
    name: "Peanut Butter Chocolate",
    price: 349,
    favorite: false,
    rating: 4.7,
    expiry: "6 months",
    img_URL: "pbchoc.jpg",
  },
  {
    id: 3,
    name: "Almond Butter Regular",
    price: 649,
    favorite: false,
    rating: 4.8,
    expiry: "6 months",
    img_URL: "ABreg.jpg",
  },
  {
    id: 4,
    name: "Almond Butter Chocolate",
    price: 749,
    favorite: false,
    rating: 4.8,
    expiry: "6 months",
    img_URL: "ABchoc.jpg",
  },
  {
    id: 5,
    name: "Hot Chocolate Premix",
    price: 399,
    favorite: false,
    rating: 4.9,
    expiry: "3 months",
    img_URL: "HotChoc.jpg",
  },
  {
    id: 6,
    name: "Cinnamon Hot Chocolate Premix",
    price: 399,
    favorite: false,
    rating: 9,
    expiry: "3 months",
    img_URL: "CinnHotChoc.jpg",
  },
  {
    id: 7,
    name: "Hazlenut Hot Chocolate Premix",
    price: 399,
    favorite: false,
    rating: 4.7,
    expiry: "3 months",
    img_URL: "HazHotChoc.jpg",
  },
];
